//
// Autogenerated by ATing-- C++ Development Framework( 1.0 )
// You can modify it to suit your application.
//


#ifndef ATing_ATING_H
#define ATing_ATING_H


namespace ATing { 




} // namespace ATing
#endif
